name:                haskell-project
version:             0.1.0.0
github:              "Xixiboo/haskell-project"
license:             BSD3
author:              "Jeremy Thiebaud - Cécile Yen"
maintainer:          ""
copyright:           "2021 Jeremy Thiebaud - Cécile Yen "

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Functional images

category: Development

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10
  - containers >= 0.5
  - bmp >= 1.2

library:
  source-dirs: src/
  ghc-options:
    - -fwarn-identities
  exposed-modules:
    - Data.FImage.Algebra
    - Data.FImage.BMP
    - Data.FImage.Geometry
    - Data.FImage.Geometry.Point
    - Data.FImage.Geometry.PolarPoint
    - Data.FImage.Geometry.Vector
    - Data.FImage.Image
    - Data.FImage.Image.Simple
    - Data.FImage.Image.Gallery
    - Data.FImage.Interval
    - Data.FImage.Transformation
    - Data.FImage.Render
    - Data.FImage.View
    - Data.FImage.Window

executables :
  haskell-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-project

tests:
  haskell-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-project